CREATE TABLE Institucion
(
    IdInstitucion INT IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(255) NOT NULL,
    Imagen VARCHAR(155) NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Institucion PRIMARY KEY CLUSTERED (IdInstitucion ASC) ON [PRIMARY]
)

CREATE TABLE Carousel
(
    IdCarousel INT IDENTITY(1,1) NOT NULL,
	Descripcion VARCHAR(255) NOT NULL,
	Imagen VARCHAR(155) NOT NULL,
	Link VARCHAR(155) NULL,
	Title VARCHAR(155) NULL,
	Target VARCHAR(15) NOT NULL DEFAULT '_self',
	Iframe VARCHAR(255) NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Carousel PRIMARY KEY CLUSTERED (IdCarousel ASC) ON [PRIMARY]
)

CREATE TABLE Noticias
(
    IdNoticia INT IDENTITY(1,1) NOT NULL,
    Title VARCHAR(255) NULL,
	Descripcion TEXT NOT NULL,
	Imagen VARCHAR(155) NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Noticias PRIMARY KEY CLUSTERED (IdNoticia ASC) ON [PRIMARY]
)

CREATE TABLE Eventos
(
    IdEvento INT IDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(155) NULL,
    Imagen VARCHAR(155) NOT NULL,
    LinkDetalle VARCHAR(155) NULL,
	Descripcion TEXT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Eventos PRIMARY KEY CLUSTERED (IdEvento ASC) ON [PRIMARY]
)

CREATE TABLE DetallesEventos
(
    IdDetalleEvento INT IDENTITY(1,1) NOT NULL,
    IdEvento INT NULL,
    Descripcion VARCHAR(255) NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_DetallesEventos PRIMARY KEY CLUSTERED (IdDetalleEvento ASC) ON [PRIMARY],
    CONSTRAINT FK_Eventos FOREIGN KEY (IdEvento) REFERENCES Eventos(IdEvento)
)

CREATE TABLE CarrerasRelacionadas
(
    IdCarreraRelacionada INT IDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(255) NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_CarrerasRelacionadas PRIMARY KEY CLUSTERED (IdCarreraRelacionada ASC) ON [PRIMARY]
)

CREATE TABLE Carreras
(
    IdCarrera INT IDENTITY(1,1) NOT NULL,
    IdCarreraRelacionada INT NOT NULL,
    Nombre VARCHAR(155) NULL,
    Imagen VARCHAR(155) NOT NULL,
    LinkDetalle VARCHAR(155) NULL,
	Descripcion VARCHAR(255) NOT NULL,
	FullDescripcion TEXT NOT NULL,
	Pensum VARCHAR(255) NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Carreras PRIMARY KEY CLUSTERED (IdCarrera ASC) ON [PRIMARY],
    CONSTRAINT FK_CarrerasRelacionadas FOREIGN KEY (IdCarreraRelacionada) REFERENCES CarrerasRelacionadas(IdCarreraRelacionada)
)

CREATE TABLE Saia
(
    IdSaia INT IDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(155) NULL,
    Imagen VARCHAR(155) NOT NULL,
    LinkDetalle VARCHAR(155) NULL,
    URLSitio VARCHAR(155) NULL,
	Descripcion VARCHAR(255) NOT NULL,
	FullDescripcion TEXT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Saia PRIMARY KEY CLUSTERED (IdSaia ASC) ON [PRIMARY]
)

CREATE TABLE AcercaDe
(
    IdAcercaDe INT IDENTITY(1,1) NOT NULL,
    Titulo VARCHAR(255) NULL,
	Descripcion VARCHAR(255) NOT NULL,
	FullDescripcion TEXT NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_AcercaDe PRIMARY KEY CLUSTERED (IdAcercaDe ASC) ON [PRIMARY]
)

CREATE TABLE Banners
(
    IdBanner INT IDENTITY(1,1) NOT NULL,
    Titulo VARCHAR(255) NULL,
	Descripcion VARCHAR(255) NOT NULL,
	FullDescripcion TEXT NOT NULL,
    Link VARCHAR(155) NULL,
    Imagen VARCHAR(155) NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
	Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Banners PRIMARY KEY CLUSTERED (IdBanner ASC) ON [PRIMARY]
)

CREATE TABLE Rol
(
     IdRol INT IDENTITY(1,1) NOT NULL ,
     Nombre VARCHAR(155) NOT NULL  ,
     CONSTRAINT PK_Rol PRIMARY KEY CLUSTERED (IdRol ASC) ON [PRIMARY]
)

CREATE TABLE Usuarios
(
    IdUsuario INT IDENTITY(1,1) NOT NULL,
    IdRol INT NOT NULL ,
    Nombres VARCHAR(155) NOT NULL  ,
    Apellidos VARCHAR(155) NOT NULL  ,
    Correo VARCHAR(155) NOT NULL UNIQUE ,
    Contrasena VARCHAR(255) NOT NULL  ,
    TokenAcceso NTEXT NULL  ,
    TokenRefresco NTEXT NULL  ,
    TokenCreado DATETIME NULL ,
    TokenExpiracion DATETIME NULL ,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
    Activo BIT NOT NULL DEFAULT 1, -- 1= ACTIVO 0= INACTIVO
    CONSTRAINT PK_Usuarios PRIMARY KEY CLUSTERED (IdUsuario ASC) ON [PRIMARY],
    CONSTRAINT FK_Rol FOREIGN KEY (IdRol) REFERENCES Rol(IdRol)
)

CREATE TABLE Auditoria
(
    IdAuditoria INT IDENTITY(1,1) NOT NULL,
    IdUsuario INT NOT NULL,
    Accion VARCHAR(15) NOT NULL,
    Tabla VARCHAR(25) NOT NULL,
    FechaCreacion DATETIME NOT NULL DEFAULT (GETDATE()),
    CONSTRAINT PK_Auditoria PRIMARY KEY CLUSTERED (IdAuditoria ASC) ON [PRIMARY],
    CONSTRAINT FK_Usuarios FOREIGN KEY (IdUsuario) REFERENCES Usuarios(IdUsuario)
)
